# https://github.com/xtoys
#
# Description: Build DockerImages using GitHub Actions
#

name: TiebaSign

on:
  workflow_dispatch:
    inputs:
      img:
        description: 'DockerImage Name'
        required: true
        default: 'tieba-sign'
      platform:
        description: 'DockerImage Platform'
        required: true
        default: 'linux/arm64,linux/amd64'

jobs:
  build:
    runs-on: ubuntu-latest
    name: Docker Build

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup QEMU Simulator
        id: qemu
        uses: docker/setup-qemu-action@v1
        with:
          image: tonistiigi/binfmt:latest
          platforms: all

      - name: Setup Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Publish image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: docker
          platforms: ${{ github.event.inputs.platform }}
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/${{ github.event.inputs.img }}:latest
